services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  web:
    image: shahriarrahman183/reactivities:v1
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    
volumes:
  postgres-data: